"""Image hosts: take generated bytes, return a public URL.

A ``Host`` puts a file and returns the URL the Ozon sheet will point at. The
default is litterbox (temporary, free, no key). Swapping to permanent R2 is a
one-config change once the user enables it — ``R2Host`` reads boto3 + env and
raises a clear, actionable error when anything required is missing.

Only ``LitterboxHost`` / ``R2Host`` touch the network; ``LocalHost`` is the
fully offline mode (returns ``file://`` URLs). Tests inject fake hosts, so the
relist pipeline runs with no network and no spend.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import requests

from .errors import OzonExcelError

LITTERBOX_ENDPOINT = "https://litterbox.catbox.moe/resources/internals/api.php"

# Env var read by get_host() to pick the default host implementation.
HOST_ENV = "OZON_RELIST_HOST"


class HostError(OzonExcelError):
    """Raised when a host cannot accept an upload or is misconfigured."""


class Host:
    """Interface: store ``data`` under ``filename`` and return its public URL."""

    name = "host"

    def put(self, filename: str, data: bytes) -> str:  # pragma: no cover - abstract
        raise NotImplementedError


class LitterboxHost(Host):
    """Temporary public host (litterbox.catbox.moe). Returns a plain-text URL.

    Verified call format:
      POST https://litterbox.catbox.moe/resources/internals/api.php
      multipart: reqtype=fileupload, time=<time>, fileToUpload=<file>
      response: the public URL as PLAIN TEXT.
    """

    name = "litterbox"

    def __init__(self, time: str = "72h", *, timeout: int = 120):
        self.time = time
        self.timeout = timeout

    def put(self, filename: str, data: bytes) -> str:
        files = {"fileToUpload": (filename, data)}
        form = {"reqtype": "fileupload", "time": self.time}
        resp = requests.post(
            LITTERBOX_ENDPOINT, data=form, files=files, timeout=self.timeout
        )
        if resp.status_code != 200:
            raise HostError(
                f"litterbox upload returned HTTP {resp.status_code}: "
                f"{resp.text[:200]!r}"
            )
        url = resp.text.strip()
        if not url.lower().startswith("http"):
            raise HostError(
                f"litterbox did not return a URL; got: {resp.text[:200]!r}"
            )
        return url


class LocalHost(Host):
    """Offline host: writes the bytes under ``root`` and returns a ``file://``
    URL. No network, no spend — useful for local dry-runs and CI."""

    name = "local"

    def __init__(self, root):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def put(self, filename: str, data: bytes) -> str:
        dest = self.root / filename
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        return dest.resolve().as_uri()


# R2 env vars (all required when R2Host is selected).
_R2_ENV = (
    "R2_ENDPOINT",
    "R2_ACCESS_KEY_ID",
    "R2_SECRET_ACCESS_KEY",
    "R2_BUCKET",
    "R2_PUBLIC_BASE",
)


class R2Host(Host):
    """Permanent host on Cloudflare R2 (S3-compatible) via boto3.

    boto3 is an OPTIONAL dependency and the R2_* env vars are not set by
    default, so this raises a clear, actionable error telling the user exactly
    what to install/set. Once R2 is enabled, switching from litterbox is a
    one-config change: set OZON_RELIST_HOST=r2 and the five R2_* vars.
    """

    name = "r2"

    def __init__(self, *, public_base: Optional[str] = None):
        try:
            import boto3  # noqa: F401  (optional dependency)
        except ImportError as exc:
            raise HostError(
                "R2 host selected but boto3 is not installed. Enable it with:\n"
                "    .venv/bin/pip install boto3\n"
                "(boto3 is an optional extra; see requirements.txt / "
                ".env.example.)"
            ) from exc

        missing = [k for k in _R2_ENV if not os.environ.get(k)]
        if missing:
            raise HostError(
                "R2 host selected but these environment variable(s) are not "
                f"set: {', '.join(missing)}. Set all of: {', '.join(_R2_ENV)} "
                "(see .env.example) before using OZON_RELIST_HOST=r2."
            )

        import boto3

        self.endpoint = os.environ["R2_ENDPOINT"]
        self.access_key = os.environ["R2_ACCESS_KEY_ID"]
        self.secret_key = os.environ["R2_SECRET_ACCESS_KEY"]
        self.bucket = os.environ["R2_BUCKET"]
        self.public_base = (public_base or os.environ["R2_PUBLIC_BASE"]).rstrip("/")
        self._client = boto3.client(
            "s3",
            endpoint_url=self.endpoint,
            aws_access_key_id=self.access_key,
            aws_secret_access_key=self.secret_key,
        )

    def put(self, filename: str, data: bytes) -> str:
        self._client.put_object(
            Bucket=self.bucket,
            Key=filename,
            Body=data,
            ContentType="image/png",
        )
        return f"{self.public_base}/{filename}"


def get_host(spec: Optional[str] = None) -> Host:
    """Resolve a host spec to a Host instance.

    spec resolution order: explicit ``spec`` arg, then env ``OZON_RELIST_HOST``,
    then the default ``"litterbox"``.

      - "litterbox"   -> LitterboxHost (default)
      - "local[:dir]" -> LocalHost (offline; dir defaults to ./relist_local)
      - "r2"          -> R2Host (requires boto3 + R2_* env; raises if missing)
    """
    if spec is None:
        spec = os.environ.get(HOST_ENV) or "litterbox"
    spec = spec.strip()
    key, _, arg = spec.partition(":")
    key = key.lower()

    if key in ("", "litterbox"):
        return LitterboxHost()
    if key == "local":
        return LocalHost(arg or "relist_local")
    if key == "r2":
        return R2Host()
    raise HostError(
        f"unknown host {spec!r}; use 'litterbox', 'local[:dir]', or 'r2'."
    )
